# NOTE: Changine this workflow will impact on all other repos that have the issue auto-assigner workflow in use

name: Issue auto-assigner
on:
    workflow_call:

jobs:
  auto_assign:
    name: Auto-assign issue to project
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: '${{ secrets.AUTO_ASSIGN_TOKEN }}'
    steps:
      - name: Assign new issues to project
        uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/orgs/OpenDataScotland/projects/3
          github-token: ${{ secrets.AUTO_ASSIGN_TOKEN }}
