name: Issue auto-assigner
on:
    workflow_call:
      secrets: 
        AUTO_ASSIGN_TOKEN:
          required: true
jobs:
  auto_assign:
    name: Auto-assign issue to project
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: '${{ secrets.AUTO_ASSIGN_TOKEN }}'
    steps:
      - name: Assign new issues to project
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event.action == 'opened'
        with:
          project: 'https://github.com/OpenDataScotland/the_od_bods/projects/3'